name: CI

# .github/workflows/ci.yml 2025-12-09
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch (or test branch github_ci push)
on:
  push:
    branches: [ master, github_ci ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-freebsd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'zint/zint'

    - name: Build FreeBSD
      id: build-freebsd
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        mem: 4096
        prepare: pkg install -y git cmake gmake gcc graphics/png qt5-core qt5-uitools qt5-buildtools qt5-qmake qt5-svg qt5-testlib
        run: |
          set -e
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git clone https://github.com/gs1/gs1-syntax-engine
          cd gs1-syntax-engine/src/c-lib
          gmake lib
          su
          gmake install
          exit
          cd ../../..
          cmake -E make_directory build
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DZINT_TEST=ON
          cmake --build build --config Release
          cd build
          QT_QPA_PLATFORM=offscreen ctest -V
